package com.zhuc.mybatis.entity;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.Id
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.name
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.time
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.Id
     *
     * @return the value of log.Id
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.Id
     *
     * @param id the value for log.Id
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.name
     *
     * @return the value of log.name
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.name
     *
     * @param name the value for log.name
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.time
     *
     * @return the value of log.time
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.time
     *
     * @param time the value for log.time
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}