package com.zhuc.mybatis.entity;

public class UserLoginKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.log_id
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_name
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.log_id
     *
     * @return the value of user_login.log_id
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.log_id
     *
     * @param logId the value for user_login.log_id
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_name
     *
     * @return the value of user_login.user_name
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_name
     *
     * @param userName the value for user_login.user_name
     *
     * @mbggenerated Fri Mar 20 10:58:00 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}