package com.zhuc.mybatis.entity;

public class UserLoginKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.logid
     *
     * @mbggenerated Wed Mar 18 14:09:53 CST 2015
     */
    private Integer logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_name
     *
     * @mbggenerated Wed Mar 18 14:09:53 CST 2015
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.logid
     *
     * @return the value of user_login.logid
     *
     * @mbggenerated Wed Mar 18 14:09:53 CST 2015
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.logid
     *
     * @param logid the value for user_login.logid
     *
     * @mbggenerated Wed Mar 18 14:09:53 CST 2015
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_name
     *
     * @return the value of user_login.user_name
     *
     * @mbggenerated Wed Mar 18 14:09:53 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_name
     *
     * @param userName the value for user_login.user_name
     *
     * @mbggenerated Wed Mar 18 14:09:53 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}