package com.zhuc.mybatis.mapper;

import com.zhuc.mybatis.entity.UserLogin;
import com.zhuc.mybatis.entity.UserLoginExample;
import com.zhuc.mybatis.entity.UserLoginKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int countByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int deleteByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int deleteByPrimaryKey(UserLoginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    List<UserLogin> selectByExample(UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    UserLogin selectByPrimaryKey(UserLoginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int updateByExample(@Param("record") UserLogin record, @Param("example") UserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int updateByPrimaryKeySelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Thu Mar 19 16:02:08 CST 2015
     */
    int updateByPrimaryKey(UserLogin record);
}